import type { Goal } from '../types';

export const mockGoals: Goal[] = [
  {
    id: '1',
    title: 'Complete UX Design Course',
    description: 'Finish the comprehensive UX design course and earn certification',
    category: 'study',
    status: 'in-progress',
    priority: 'high',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    timeSpent: 0,
    subGoals: [
      {
        id: '1-1',
        title: 'Complete Module 1: Introduction to UX',
        completed: true,
        createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
        completedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
      },
      {
        id: '1-2',
        title: 'Complete Module 2: User Research',
        completed: true,
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
        completedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      },
      {
        id: '1-3',
        title: 'Complete Module 3: Wireframing',
        completed: false,
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        deadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
      },
      {
        id: '1-4',
        title: 'Complete Final Project',
        completed: false,
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
        deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
      },
    ],
  },
  {
    id: '2',
    title: 'Run 5K Marathon',
    description: 'Train and complete a 5K marathon in under 30 minutes',
    category: 'fitness',
    status: 'in-progress',
    priority: 'medium',
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
    timeSpent: 0,
    subGoals: [
      {
        id: '2-1',
        title: 'Run 3 times per week',
        completed: true,
        createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
        completedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      },
      {
        id: '2-2',
        title: 'Increase distance to 4K',
        completed: false,
        createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
        deadline: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
      },
    ],
  },
  {
    id: '3',
    title: 'Read 12 Books This Year',
    description: 'Read one book per month to expand knowledge and improve reading habits',
    category: 'personal',
    status: 'in-progress',
    priority: 'low',
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000),
    deadline: new Date(new Date().getFullYear(), 11, 31),
    timeSpent: 0,
    subGoals: [
      {
        id: '3-1',
        title: 'Read "Atomic Habits"',
        completed: true,
        createdAt: new Date(Date.now() - 80 * 24 * 60 * 60 * 1000),
        completedAt: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000),
      },
      {
        id: '3-2',
        title: 'Read "The Design of Everyday Things"',
        completed: true,
        createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
        completedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
      },
      {
        id: '3-3',
        title: 'Read "Don\'t Make Me Think"',
        completed: false,
        createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
        deadline: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
      },
    ],
  },
  {
    id: '4',
    title: 'Save $5,000 Emergency Fund',
    description: 'Build an emergency fund to cover 3 months of expenses',
    category: 'finance',
    status: 'not-started',
    priority: 'high',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    deadline: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000),
    timeSpent: 0,
    subGoals: [
      {
        id: '4-1',
        title: 'Set up automatic savings',
        completed: false,
        createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
        deadline: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
      },
      {
        id: '4-2',
        title: 'Save first $1,000',
        completed: false,
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
      },
    ],
  },
  {
    id: '5',
    title: 'Learn Spanish',
    description: 'Achieve conversational level in Spanish',
    category: 'personal',
    status: 'in-progress',
    priority: 'medium',
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    deadline: new Date(Date.now() + 150 * 24 * 60 * 60 * 1000),
    timeSpent: 0,
    subGoals: [
      {
        id: '5-1',
        title: 'Complete Duolingo basics',
        completed: true,
        createdAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000),
        completedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
      },
      {
        id: '5-2',
        title: 'Practice 15 minutes daily',
        completed: false,
        createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
        deadline: new Date(Date.now() + 120 * 24 * 60 * 60 * 1000),
      },
    ],
  },
  {
    id: '6',
    title: 'Save 1000 PLN',
    description: 'Save 1000 PLN for vacation',
    category: 'finance',
    status: 'in-progress',
    priority: 'high',
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
    deadline: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    timeSpent: 0,
    isFinalGoal: true,
    mainGoalCompleted: false,
    subGoals: [
      {
        id: '6-1',
        title: 'Save 500 PLN',
        completed: true,
        createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
        completedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
      },
      {
        id: '6-2',
        title: 'Save another 250 PLN',
        completed: false,
        createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
        deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
      },
    ],
  },
];

